<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup Label="Build">
    <TargetFramework>net7.0</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Label="Package">
    <Version>0.0.0.1</Version>
    <Authors>Алексей Якубин</Authors>
    <Company>Делобайты</Company>
    <Product>Delobytes.Backend</Product>
    <Description>Бекенд</Description>
    <Copyright>Авторские права © Делобайты 2026. Все права защищены</Copyright>
    <PackageId>Delobytes.Backend</PackageId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="7.1.0" />
    <PackageReference Include="Delobytes.AspNetCore.Common" Version="2.0.0" />
    <PackageReference Include="Delobytes.Extensions.Configuration" Version="1.0.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.4.1" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="7.0.20" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.20">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="7.0.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="2.3.0" />
    <PackageReference Include="Serilog.Enrichers.MassTransitMessage" Version="2.0.0" />
    <PackageReference Include="Serilog.Enrichers.Process" Version="2.0.2" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="3.1.0" />
    <PackageReference Include="Serilog.Exceptions" Version="8.4.0" />
    <PackageReference Include="Serilog.Exceptions.EntityFrameworkCore" Version="8.4.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
    <PackageReference Include="Serilog.Sinks.OpenSearch" Version="2.0.0" />
    <PackageReference Include="SerilogAnalyzer" Version="0.15.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules\Identity\Delobytes.App.Backend.Identity.Infrastructure\Delobytes.App.Backend.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Catalog\Delobytes.App.Backend.Catalog.Infrastructure\Delobytes.App.Backend.Catalog.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Pricing\Delobytes.App.Backend.Pricing.Infrastructure\Delobytes.App.Backend.Pricing.Infrastructure.csproj" />
  </ItemGroup>

</Project>
