using Delobytes.App.Backend.Integrations.Contracts.Events;
using MassTransit;

namespace Delobytes.App.Backend.Integrations.Infrastructure.Messaging.Consumers;

/// <summary>
/// MassTransit consumer adapter for ProcessProductImportBatchCompletedConsumer.
/// Extracts MessageId from ConsumeContext and passes it through for idempotency.
/// </summary>
public class ProcessProductImportBatchCompletedMassTransitConsumer : IConsumer<ProductImportBatchCompletedEvent>
{
    private readonly ProcessProductImportBatchCompletedConsumer _consumer;

    /// <summary>
    /// Initializes a new instance of the <see cref="ProcessProductImportBatchCompletedMassTransitConsumer"/> class.
    /// </summary>
    public ProcessProductImportBatchCompletedMassTransitConsumer(ProcessProductImportBatchCompletedConsumer consumer)
    {
        _consumer = consumer;
    }

    /// <inheritdoc/>
    public async Task Consume(ConsumeContext<ProductImportBatchCompletedEvent> context)
    {
        // MessageId is generated by MassTransit and is stable across redeliveries of the same message.
        Guid messageId = context.MessageId ?? Guid.NewGuid();
        await _consumer.ProcessAsync(context.Message, messageId, context.CancellationToken);
    }
}
